### PR TITLE
Upgrade example to work with React 0.14

### PR DESCRIPTION
**Pull request by joshwnj**
Example is upgraded, and I've also confirmed that everything works without the `transform` field in package.json so have removed that, as @mvila noted in #11 

@kof & @kompot do you see anything else that should be updated before we publish v3.0.0?

### CODE REVIEW

**Comment by kof** [comment]
ok for me

**Comment by kof** [comment]
lets release a new version

**Comment by kompot** [comment]
Yep, seems ok.

**Comment by boccob** [comment]
Guys, when do you plan to release nev version?

**Comment by kof** [comment]
only @joshwnj has access to npm

**Comment by joshwnj** [comment]
On it now. And will fix the npm access too :)

**Comment by joshwnj** [comment]
Published v3.0.0 - thanks all

**Pull request merged**
