### PR TITLE
support react 0.14

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by joshwnj** [comment]
Thanks @kof - nearly ready to upgrade to 0.14 just need to fix some things in `example/main.js` first. 

On another note, would you consider joining as a collaborator? I've really appreciated your help on this and would love to share the ownership.

**Comment by kof** [comment]
> Thanks @kof - nearly ready to upgrade to 0.14 just need to fix some things in example/main.js first.

yep and also tests need to be updated.

>On another note, would you consider joining as a collaborator? I've really appreciated your help on this and would love to share the ownership.

Sure.

**Comment by kof** [comment]
One problem I stumbled  over while chaning tests:

`Invariant Violation: onlyChild must be passed a children with exactly one child.``

I logged `this.props.children.length` in render method and got "2". For some reason even without children we have still children there ... weird ... 

any ideas?

**Comment by kof** [comment]
@joshwnj try to pull from my branch, don't forget to rm node_modules and install again.

**Comment by boccob** [comment]
@kof It stops working starting from reactify 0.15 (have no idea why). 
Actually check #19. I don't know why there are two pull request with the same thing.

**Comment by boccob** [comment]
@kof Just get rid of React.createFactory in https://github.com/ubergrape/react-visibility-sensor/blob/master/tests/visibility-sensor-spec.jsx#L22 and it will work fine with last reactify.

**Comment by joshwnj** [comment]
Good find, thanks @boccob

**Comment by joshwnj** [comment]
I'll merge now and apply the fix in master

**Pull request merged**
