### PR TITLE
Make `react-visibility-sensor` support server rendering.

### PR DESCRIPTION
**Pull request by kompot**
Obviously, using Element in PropTypes breaks server rendering.

Use an `if` to overcome that. Better solution is highly appreciated.

### CODE REVIEW

**Comment by joshwnj** [comment]
Sure, this looks good thanks. 

Btw I'm curious to know, what kind of application are you using this in?

**Comment by kompot** [comment]
Well it's an online betting app that should subscribe to live updates only those games that are visible.
But we also have server rendering for better initial performance.

**Comment by joshwnj** [comment]
Thanks for the info. I had to shuffle some versions around this morning due to a breaking change, so please update your package.json to use `^2.0.0` to get this update.  I can also apply this to the v1.x branch if you need, but where possible I want to encourage moving to the new major version.

**Comment by kompot** [comment]
Yeah, seems like "might break" change to me, so better upgrade to 2.x imho.

**Pull request merged**
