### PR TITLE
Upgrade to React 0.14.

### PR DESCRIPTION
**Pull request by kompot**

### CODE REVIEW

**Comment by kompot** [comment]
Sorry,
moved reactify to dev deps and then saw this issue
https://github.com/joshwnj/react-visibility-sensor/issues/11

**Comment by joshwnj** [comment]
Looking good, thanks! Sorry for the delay, I'm nearly ready to merge this but just need to finish upgrading example/main.js - hoping to have some time this weekend for it.

On another note, would you consider joining as a collaborator? I've really appreciated your help on this and would love to share the ownership.

**Comment by kompot** [comment]
Yeah, I'll be glad to, thanks.

**Comment by joshwnj** [comment]
Hi @kompot I'll close this now as there was another upgrade in #22 which also uncovered some bugs with a newer version of reactify.

Thanks for your help here!

**Pull request closed without merging**
