### PR TITLE
 Update to ES6 style React and replaced Browserify with Webpack

### PR DESCRIPTION
**Pull request by jphamilton**
Replaced Browserify with Webpack and updated the code base to a more modern JS style (classes for React components, arrow functions, const, let). Updated packages to latest versions (including React 16)

I'm using my fork in a production app and thought I'd pass along the changes.

### CODE REVIEW

**Comment by jphamilton** [comment]
Ok, so this failed because node version is ancient?

**Comment by joshwnj** [comment]
Thanks @jphamilton there's some good stuff here. I certainly plan to merge this but first need to address some other things, to avoid merge conflicts.

**Comment by joshwnj** [comment]
Update: I'll be upgrading node version and dependencies first, before doing any rewrites of syntax (#127)

**Comment by dylmye** [comment]
Any update on this now #127 is in?

**Comment by joshwnj** [comment]
@jphamilton @dylmye I've fixed conflicts, merged and published to v5.0.1

Thanks again!

**Pull request merged**
