### PR TITLE
check if element has a size (#50)

### LINKED ISSUE #50: Reporting isVisible for free element
For elements that do not have a size in the DOM, `react-visibility-sensor` currently reports that it is visible.

I think this should be the first check:

``` javascript
if (rect.top + rect.right + rect.bottom + rect.left + rect.width === 0) {
  isVisible = false;
}
```

### PR DESCRIPTION
**Pull request by skovhus**
Fixes #50... Sorry that I didn't add any tests for this. Could be nice with some unit tests.

Maybe look at this with whitespace disabled: https://github.com/joshwnj/react-visibility-sensor/pull/51/files?w=0

### CODE REVIEW

**Comment by eek** [comment]
Can you remove the indentation changes?

**Comment by joshwnj** [comment]
Hi @skovhus , just wanted to touch base here. I'm keen to give your PR a proper review and merge but if you could first rebase & remove the whitespace changes it would really help. Thanks!

**Comment by skovhus** [comment]
I cannot release remove white space as the whole block is indented. Would be really great to refactor that giant function. 

But I will rebase. ; )

**Comment by joshwnj** [comment]
Ah ok - yeah we do need to split up this giant function at some point :) I'm thinking of putting together a big major-version roadmap for early 2017, and this would definitely be on the cards.

> I cannot release remove white space as the whole block is indented.

That's cool, but in that case could you please point out specifically what things you are changing? Just a bit difficult to see in the current diff :)

Thanks

**Comment by skovhus** [comment]
The diff without whitespace makes it fairly clear I think https://github.com/joshwnj/react-visibility-sensor/pull/51/files?w=0

But let me do an updated PR

**Comment by joshwnj** [comment]
Oh that is heaps better, thanks :) I have to remember that `?w=0` trick 😆

**Comment by skovhus** [comment]
I've updated the PR by rebasing with master, but I would like one of you to manually test this change. 

More unit tests are required here in order to make a change like this safe.

**Comment by igorz-** [comment]
Hi! Could someone please tell when this will be merged? Or there are some better solution?

**Comment by joshwnj** [comment]
superceded by #114

**Comment by joshwnj** [comment]
Hi @igorz- & @skovhus, can you please check if the latest version is working for you? Thanks!

**Pull request closed without merging**
